name: Deploy Profile Site

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: SSH Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /home/opc/profile
          git pull origin main
          npm install

          # optional: re-build if needed (for Next.js or production setup)
          # npm run build

          pm2 start npm --name profile -- run dev -- --hostname 0.0.0.0 --port 3000 || pm2 restart profile
          pm2 save